### ISSUE TITLE
まれにエラーが出て閲覧できない

### ISSUE THREAD

**Issue by gulping** [suzuki86/qrank-apiserver#32]
http://qrank.wbsrv.net/entries?days=1&orderby=like_count

(などのentriesページ)にアクセスした際、体感では数十回に1回くらいの確率で

`Warning: unlink(tmp/cache.storage//files/rankingtags.c.html): No such file or directory in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/lib/php_fast_cache.php on line 901`

などのエラーが画面上に表示され、ページが表示されたりされなかったりする

----
直近では2017/12/01 15:48(日本時間)ごろにアクセスした際に出ました。

----

----
追記：

2017/12/20 14:00(日本時間)
`Warning: file_get_contents(tmp/cache.storage//files/rankingtags.c.html): failed to open stream: No such file or directory in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/lib/php_fast_cache.php on line 893`

コードを読んでないので的外れかもですが、エラー文中のパス中の`//`部分が怪しい気がします

----

----
2017/12/26 13:31(日本時間)
`Warning: unlink(tmp/cache.storage//files/entriesdays1orderbylike_count.c.html): No such file or directory in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/lib/php_fast_cache.php on line 974

Warning: unlink(tmp/cache.storage//files/entriesdays7orderbylike_count.c.html): No such file or directory in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/lib/php_fast_cache.php on line 974

Warning: unlink(tmp/cache.storage//files/rankingtags.c.html): No such file or directory in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/lib/php_fast_cache.php on line 974`

**Comment by suzuki86** [comment]
@gulping お知らせありがとうございます :pray:  確認します！

**Comment by gulping** [comment]
2018/01/10 15:19(日本時間)
```
Warning: file_get_contents(http://133.130.89.127/api/v1/ranking/tags): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 28

Warning: array_slice() expects parameter 1 to be array, null given in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 33
500 Internal Server Error
Invalid argument supplied for foreach() (2)
#0 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/views/sidebar.php(73): flight\Engine->handleError(2, 'Invalid argumen...', '/export/sd206/w...', 73, Array)
#1 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/template/View.php(125): include('/export/sd206/w...')
#2 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(441): flight\template\View->render('sidebar.php', NULL)
#3 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(195): flight\Engine->_render('sidebar.php')
#4 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#6 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(64): flight\core\Dispatcher->run('render', Array)
#7 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(195): flight\Engine->__call('render', Array)
#8 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(195): flight\Engine->render('sidebar.php')
#9 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#10 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/views/entries.php(16): Flight::__callStatic('render', Array)
#11 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/views/entries.php(16): Flight::render('sidebar.php')
#12 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/template/View.php(125): include('/export/sd206/w...')
#13 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(441): flight\template\View->render('entries.php', Array)
#14 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(199): flight\Engine->_render('entries.php', Array)
#15 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#16 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#17 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(64): flight\core\Dispatcher->run('render', Array)
#18 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(199): flight\Engine->__call('render', Array)
#19 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(199): flight\Engine->render('entries.php', Array)
#20 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#21 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(133): Flight::__callStatic('render', Array)
#22 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(133): Flight::render('entries.php', Array)
#23 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(160): {closure}()
#24 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#25 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(313): flight\core\Dispatcher::execute(Object(Closure), Array)
#26 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(191): flight\Engine->_start()
#27 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#28 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#29 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#30 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#31 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(191): flight\Engine->start()
#32 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#33 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(154): Flight::__callStatic('start', Array)
#34 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(154): Flight::start()
#35 {main}
```

2018/01/23 17:08(日本時間)
```
Warning: file_get_contents(http://133.130.89.127/api/v1/ranking/tags): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 28

Warning: array_slice() expects parameter 1 to be array, null given in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 33
500 Internal Server Error
Invalid argument supplied for foreach() (2)
#0 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/views/sidebar.php(73): flight\Engine->handleError(2, 'Invalid argumen...', '/export/sd206/w...', 73, Array)
#1 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/template/View.php(125): include('/export/sd206/w...')
#2 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(441): flight\template\View->render('sidebar.php', NULL)
#3 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(195): flight\Engine->_render('sidebar.php')
#4 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#6 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(64): flight\core\Dispatcher->run('render', Array)
#7 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(195): flight\Engine->__call('render', Array)
#8 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(195): flight\Engine->render('sidebar.php')
#9 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#10 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/views/entries.php(16): Flight::__callStatic('render', Array)
#11 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/views/entries.php(16): Flight::render('sidebar.php')
#12 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/template/View.php(125): include('/export/sd206/w...')
#13 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(441): flight\template\View->render('entries.php', Array)
#14 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(199): flight\Engine->_render('entries.php', Array)
#15 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#16 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#17 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(64): flight\core\Dispatcher->run('render', Array)
#18 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(199): flight\Engine->__call('render', Array)
#19 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(199): flight\Engine->render('entries.php', Array)
#20 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#21 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(133): Flight::__callStatic('render', Array)
#22 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(133): Flight::render('entries.php', Array)
#23 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(160): {closure}()
#24 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#25 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(313): flight\core\Dispatcher::execute(Object(Closure), Array)
#26 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(191): flight\Engine->_start()
#27 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#28 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#29 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#30 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#31 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/core/Dispatcher.php(191): flight\Engine->start()
#32 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#33 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(154): Flight::__callStatic('start', Array)
#34 /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php(154): Flight::start()
#35 {main}
```

2018/4/11, 4/12も同様のエラーが再現

**Comment by suzuki86** [comment]
@gulping ありがとうございます！

**Comment by gulping** [comment]
http://qrank.wbsrv.net/entries?days=1&orderby=like_count
```
Warning: file_get_contents(http://133.130.89.127/api/v1/entries/count): failed to open stream: HTTP request failed! in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 51
```

**Comment by suzuki86** [comment]
@gulping お知らせありがとうございます！
API サーバーが死んでいたので復旧させました。

**Comment by gulping** [comment]
2018/07/04

10:10

```
Warning: file_get_contents(http://133.130.89.127/api/v1/entries/count): failed to open stream: HTTP request failed! in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 51

Warning: file_get_contents(http://133.130.89.127/api/v1/ranking/tags): failed to open stream: HTTP request failed! in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 26

Warning: array_slice() expects parameter 1 to be array, null given in /export/sd206/www/jp/r/e/gmoserver/9/8/sd0300498/qrank.wbsrv.net/index.php on line 31
```

10:20

```
504 Gateway Time-out

Gateway Time-out
The gateway did not receive a timely response from the upstream server or application.
```

**Comment by suzuki86** [comment]
@gulping ありがとうございます！
復旧させました :pray:
